---

roles:
  - name: jonaspammer.bootstrap
  - name: 0x0i.systemd

collections:
  - containers.podman
  - ansible.posix
  - community.general
  - name: https://github.com/aconitumnapellus/adfinis.facts
    type: git
    version: main
