---

roles:
  - name: jonaspammer.bootstrap
  # @TODO: Use the galaxy uri again once a new release has been created
  - name: https://github.com/O1ahmad/ansible-role-systemd

collections:
  - containers.podman
  - ansible.posix
  - community.general
  - adfinis.facts
