---

- name: create sync dirs
  file:
    path: "{{ repo_mirror_base_path }}/{{ item.name }}"
    state: directory
    mode: 0755
    owner: '{{ item.user | default(repo_mirror_user) }}'
    group: '{{ item.group | default(repo_mirror_group) }}'
  with_items: "{{ repo_mirror_repos }}"
  when: item is defined and item
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:configuration'

- name: create log dirs
  file:
    dest: "{{ repo_mirror_log_path }}/{{ item.name }}"
    state: directory
    mode: 0755
    owner: '{{ item.user | default(repo_mirror_user) }}'
    group: '{{ item.group | default(repo_mirror_group) }}'
  with_items: "{{ repo_mirror_repos }}"
  when: item is defined and item
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:configuration'

- name: create mirroring scripts
  template:
    src: "usr/local/bin/{{ item.type }}_mirror.j2"
    dest: "/usr/local/bin/mirror_{{ item.name }}.sh"
    owner: '{{ item.user | default(repo_mirror_user) }}'
    group: root
    mode: 0740
  with_items: "{{ repo_mirror_repos }}"
  when: item is defined and item
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:configuration'
    - 'role::repo_mirror:configuration:script'

- name: create log rotation config
  template:
    src: etc/logrotate.d/config.template.j2
    dest: '/etc/logrotate.d/{{ item.name }}'
    owner: root
    group: root
    mode: 0744
  with_items: '{{ repo_mirror_repos }}'
  when: item is defined and item
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:configuration'

- name: populate timer facts
  timer_facts:

- name: populate service facts
  service_facts:

- name: validate calendar format
  ansible.builtin.command:
    argv:
      - "systemd-analyze"
      - "calendar"
      - "{{ repo_systemd_timer }}"
  register: systemd_analyze_output
  failed_when: systemd_analyze_output.rc != 0

- name: Create mirror systemd units
  include_role:
    name: 0x0i.systemd
  vars:
    unit_config:
      - name: "sync_{{ item.name }}_mirror"
        type: service
        Unit:
          Description: "Systemd unit for mirror script of {{ item.name }}"
        Service:
          Type: simple
          ExecStart: "/usr/local/bin/mirror_{{ item.name }}.sh"
          KillMode: process
          RuntimeMaxSec: "{{ item.systemd_unit_max_runtime_sec }}"
  with_items: "{{ repo_mirror_repos }}"
  when: item is defined and item and item.disabled is not defined
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:configuration'
    - 'role::repo_mirror:configuration:timer'

- name: Create mirror systemd timer units and enable
  include_role:
    name: 0x0i.systemd
  vars:
    unit_config:
      - name: "sync_{{ item.name }}_mirror"
        type: timer
        Unit:
          Description: "Systemd timer unit for mirror script of {{ item.name }}"
        Timer:
          OnCalendar: "{{ hostvars[item].backup_dirvish_timepoint }}"
          Persistent: false
        Install:
          WantedBy: "timers.target"
        enabled: "{{ not item.systemd_timer_disabled }}"
        state: "started"
  with_items: "{{ repo_mirror_repos }}"
  when: item is defined
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:configuration'
    - 'role::repo_mirror:configuration:unit'

- name: create fedora report script config dir
  file:
    path: /etc/mirror
    owner: mirror
    group: mirror
    state: directory
  when: repo_mirror_fedora_report and repo_mirror_fedora_reports is defined and repo_mirror_fedora_reports
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:configuration'
    - 'role::repo_mirror:configuration:fedora_report'


- name: create fedora report script config
  template:
    src: templates/etc/mirror/fedora_report.conf.j2
    dest: /etc/mirror/fedora_report.conf
    owner: mirror
    group: mirror
    mode: 0640
  when: repo_mirror_fedora_report and repo_mirror_fedora_reports is defined and repo_mirror_fedora_reports
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:configuration'
    - 'role::repo_mirror:configuration:fedora_report'

- name: copy fedora report script
  copy:
    src: files/report_mirror
    dest: /usr/local/bin/report_mirror
    owner: mirror
    group: mirror
    mode: 0750
  when: repo_mirror_fedora_report
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:configuration'
    - 'role::repo_mirror:configuration:fedora_report'
