---

- name: Include os specific vars
  ansible.builtin.include_tasks: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
    - '{{ ansible_os_family }}.yml'
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:installation'
    - 'role::repo_mirror:configuration'

- name: Include installation tasks
  ansible.builtin.include_tasks: installation.yml
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:installation'

- name: Include configuration tasks
  ansible.builtin.include_tasks: configuration.yml
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:configuration'
    - 'role::repo_mirror:configuration:script'
