---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: podman
platforms:
  - name: instance
    image: docker.io/debian:bullseye
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
